#ifndef _config_h
#define _config_h

#define MAXLINE 8192
#define MAXPATH 8192
#define MAXKSTNM 2048
#define MAXNAME 255
#define MAXBAND 100
#define MAX_SKIP_STEPS_SIZE 100
#define MAX_GPU_DEVICES 64
#define _RISTRICT_MAX_GPU_BATCH 9999999
#define _RISTRICT_MAX_CPU_BATCH 9999999
#define MAXVAL 20
#define MINVAL 1e-30

#define WHITEN_NONE 0
#define WHITEN_BEFORE_NORMALIZE 1
#define WHITEN_AFTER_NORMALIZE 2
#define WHITEN_BEFORE_AND_AFTER 3

#define NORMALIZE_NONE 0
#define NORMALIZE_RUNABS_MF 1
#define NORMALIZE_ONEBIT 2
#define NORMALIZE_RUNABS 3

#define OUTPUT_KEEP_AMPLITUDE 0
#define OUTPUT_PHASE_ONLY 1

#endif
